export { default as Home } from './Home'
export { default as Profile } from './Profile'
export { default as Task } from './Task'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as NotFound } from './NotFound'
export { default as PostTask } from './PostTask'